---
- name: add backports repository
  apt_repository: repo='deb http://ftp.debian.org/debian wheezy-backports main' state=present update_cache=yes
  when: ansible_distribution == "Debian"
  tags:
   - haproxy_install

# http://haproxy.debian.net/#?distribution=Ubuntu&release=trusty&version=1.6
- name: Install haproxy repository
  apt_repository:
    repo='ppa:vbernat/haproxy-1.6'
  when: ansible_distribution == "Ubuntu"
  tags:
   - haproxy_install

- name: install haproxy
  apt:
    pkg=haproxy
    state=installed
    update_cache=yes
  tags:
   - haproxy_install
