---
# tasks file for ansible-haproxy-role
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: start haproxy
  service: name=haproxy state=started
  tags:
   - haproxy_service

- name: copy haproxy default config
  copy: src='default.cfg' dest='/etc/default/haproxy'
  tags:
   - haproxy_install

- name: configure haproxy
  template: src=main.cfg dest=/etc/haproxy/haproxy.cfg
  notify: reload haproxy
  tags:
   - haproxy_configure

- name: enable haproxy
  systemd:
    name: haproxy
    state: started
    enabled: true