---
- name: install the libselinux-python package
  yum: name=libselinux-python state=installed
  tags:
   - haproxy_install

- name: install haproxy
  yum: name=haproxy state=present
  tags:
   - haproxy_install
